import type { LibraryDocument } from '@/types/library';

export const libraryDocuments: LibraryDocument[] = [
  {
    id: 'doc-1',
    title: 'Whipple Procedure',
    specialties: ['Oncology', 'Gastroenterology'],
    documentType: 'Patient Education Text',
    version: 'v1',
    addedAt: 'Sep 8, 2026, 9:00 AM UTC',
    lastScannedAt: null,
    highestRisk: null,
    findings: null,
  },
  {
    id: 'doc-2',
    title: 'Human Bite Care',
    specialties: ['Emergency Medicine'],
    documentType: 'Patient Education Text',
    version: 'v1',
    addedAt: 'Sep 6, 2026, 9:00 AM UTC',
    lastScannedAt: null,
    highestRisk: null,
    findings: null,
  },
  {
    id: 'doc-3',
    title: 'Post-Op Wound Care Guide',
    specialties: ['Unassigned'],
    documentType: 'Patient Education Text',
    version: 'v1',
    addedAt: 'Sep 6, 2026, 9:00 AM UTC',
    lastScannedAt: null,
    highestRisk: null,
    findings: null,
  },
  {
    id: 'doc-4',
    title: 'Cardiac Rehab Protocol',
    specialties: ['Cardiology'],
    documentType: 'Video Script',
    version: 'v1',
    addedAt: 'Sep 6, 2026, 9:00 AM UTC',
    lastScannedAt: null,
    highestRisk: null,
    findings: null,
  },
  {
    id: 'doc-5',
    title: 'Circumcision Care',
    specialties: ['Pediatrics', 'Urology'],
    documentType: 'Patient Education Text',
    version: 'v1',
    addedAt: 'Sep 1, 2026, 9:00 AM UTC',
    lastScannedAt: 'Sep 1, 2026, 9:00 AM UTC',
    highestRisk: 'medium',
    findings: 5,
  },
  {
    id: 'doc-6',
    title: 'Famotidine',
    specialties: ['Gastroenterology'],
    documentType: 'Medication',
    version: 'v1',
    addedAt: 'Sep 1, 2026, 9:00 AM UTC',
    lastScannedAt: 'Sep 1, 2026, 9:00 AM UTC',
    highestRisk: 'low',
    findings: 2,
  },
  {
    id: 'doc-7',
    title: 'Pterygium',
    specialties: ['Unassigned'],
    documentType: 'Patient Education Text',
    version: 'v1',
    addedAt: 'Sep 1, 2026, 9:00 AM UTC',
    lastScannedAt: 'Sep 1, 2026, 9:00 AM UTC',
    highestRisk: 'low',
    findings: 2,
  },
];
